# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PerplexityMcp < Formula
  desc "A Model Context Protocol (MCP) server for the Perplexity API"
  homepage "https://github.com/Alcova-AI/perplexity-mcp"
  version "0.2.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/Alcova-AI/perplexity-mcp/releases/download/v0.2.1/perplexity-mcp_Darwin_x86_64.tar.gz"
      sha256 "b20591baac885d66764129b805f854ebcbe9d1242b54fea98b4dd9a1878a5b8c"

      def install
        bin.install "perplexity-mcp"
      end
    end
    on_arm do
      url "https://github.com/Alcova-AI/perplexity-mcp/releases/download/v0.2.1/perplexity-mcp_Darwin_arm64.tar.gz"
      sha256 "9a91eec25b9df32995f9f21c7035b581699f07a80aba2dcb14aa7e22aa4095bd"

      def install
        bin.install "perplexity-mcp"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Alcova-AI/perplexity-mcp/releases/download/v0.2.1/perplexity-mcp_Linux_x86_64.tar.gz"
        sha256 "20725ea7955a4b569dfa289d44f572c369acc5c6b17d23ff1ccfc7dc87526319"

        def install
          bin.install "perplexity-mcp"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Alcova-AI/perplexity-mcp/releases/download/v0.2.1/perplexity-mcp_Linux_arm64.tar.gz"
        sha256 "bbf22a12e6f7aec7ada131eccc107f4ba172ecdeaccd3b9e5bd8aae537bf457f"

        def install
          bin.install "perplexity-mcp"
        end
      end
    end
  end

  test do
    system "#{bin}/perplexity-mcp --help"
  end
end
