# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PerplexityMcp < Formula
  desc "A Model Context Protocol (MCP) server for the Perplexity API"
  homepage "https://github.com/Alcova-AI/perplexity-mcp"
  version "0.2.6"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Alcova-AI/perplexity-mcp/releases/download/v0.2.6/perplexity-mcp_Darwin_x86_64.tar.gz", using: CurlDownloadStrategy
      sha256 "2ccbcd90cf9dfe80c3621a05b19c6bbf26654bde9a365c062f364914868a3248"

      def install
        bin.install "perplexity-mcp"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Alcova-AI/perplexity-mcp/releases/download/v0.2.6/perplexity-mcp_Darwin_arm64.tar.gz", using: CurlDownloadStrategy
      sha256 "4ba12ee79488402f333e9ed44545c75f5d084745af62de301a76735e1635d489"

      def install
        bin.install "perplexity-mcp"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Alcova-AI/perplexity-mcp/releases/download/v0.2.6/perplexity-mcp_Linux_x86_64.tar.gz", using: CurlDownloadStrategy
        sha256 "8a43434a095cc03b2c1c929f05cef7b24c99ea2ef5812a5a1bbd56182d0cd8cb"

        def install
          bin.install "perplexity-mcp"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Alcova-AI/perplexity-mcp/releases/download/v0.2.6/perplexity-mcp_Linux_arm64.tar.gz", using: CurlDownloadStrategy
        sha256 "ce11bf7b617512730f22eb2c33fbd66037ef7b70f14d2b75622a57ae0284f588"

        def install
          bin.install "perplexity-mcp"
        end
      end
    end
  end

  test do
    system "#{bin}/perplexity-mcp --help"
  end
end
